### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by ryanlebreton-gmu** [jmacario-gmu/gmuj-wordpress-theme-mason-twentytwenty-child#25]
Minor update: OUB asked if the footer links that point to www2 (Privacy Statement and FOIA) could be updated to www.

**Comment by jmacario-gmu** [comment]
Great, thanks!

From: ryanlebreton-gmu ***@***.***>
Sent: Thursday, August 25, 2022 11:30 AM
To: jmacario-gmu/gmuj-wordpress-theme-mason-twentytwenty-child ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jmacario-gmu/gmuj-wordpress-theme-mason-twentytwenty-child] Footer links (Issue #25)


Minor update: OUB asked if the footer links that point to www2 (Privacy Statement and FOIA) could be updated to www.

-

**Comment by jmacario-gmu** [comment]
This has been fixed via commit 9bb049de
